[pihole_index]
definition = index=pihole
iseval = 0

[pihole_queries]
definition = index=pihole sourcetype=pihole:query:json event_type=dns_query
iseval = 0

[pihole_metrics]
definition = index=pihole sourcetype=pihole:metric:json event_type=pihole_metric
iseval = 0

[pihole_blocked]
definition = `pihole_queries` action=blocked
iseval = 0

[pihole_allowed]
definition = `pihole_queries` action=allowed
iseval = 0
