[pihole:query:json]
EVAL-pihole_node = coalesce(pihole_node, host)
EVAL-app = "dns"
EVAL-vendor_product = coalesce(vendor_product, "Pi-hole FTL")
EVAL-answer = coalesce(reply_value, reply_code)
EVAL-dest = coalesce(dest, upstream)
EVAL-src = coalesce(src, src_ip)
EVAL-query = coalesce(query, domain)
EVAL-query_type = coalesce(query_type, record_type)
FIELDALIAS-pihole_client = src AS client_ip
FIELDALIAS-pihole_domain = query AS dns_query

[pihole:metric:json]
EVAL-pihole_node = coalesce(pihole_node, host)

[pihole:dns]
EVAL-pihole_node = coalesce(pihole_node, host)

[pihole:ftl]
EVAL-pihole_node = coalesce(pihole_node, host)

[pihole:web]
EVAL-pihole_node = coalesce(pihole_node, host)
