[eventtype=pihole_dns_query]
dns = enabled
network = enabled

[eventtype=pihole_dns_blocked]
dns = enabled
network = enabled
blocked = enabled

[eventtype=pihole_dns_allowed]
dns = enabled
network = enabled
allowed = enabled
