[monitor:///var/log/pihole/pihole.log]
disabled = 0
index = pihole
sourcetype = pihole:dns
host = pihole-10.0.0.223

[monitor:///var/log/pihole/FTL.log]
disabled = 0
index = pihole
sourcetype = pihole:ftl
host = pihole-10.0.0.223

[monitor:///var/log/pihole/webserver.log]
disabled = 0
index = pihole
sourcetype = pihole:web
host = pihole-10.0.0.223

[script://$SPLUNK_HOME/etc/apps/TA-pihole/bin/pihole_queries.py]
disabled = 0
interval = 30
index = pihole
sourcetype = pihole:query:json
host = pihole-10.0.0.223

[script://$SPLUNK_HOME/etc/apps/TA-pihole/bin/pihole_metrics.py]
disabled = 0
interval = 60
index = pihole
sourcetype = pihole:metric:json
host = pihole-10.0.0.223
