[tcpout]
defaultGroup = pihole_splunk
forwardedindex.0.whitelist = .*

[tcpout:pihole_splunk]
server = 10.0.0.230:9997
autoLB = true
compressed = true
useACK = true

[tcpout-server://10.0.0.230:9997]
